using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using HebrewBooks.Core.Abstractions;
using HebrewBooks.Core.Models;
using HebrewBooks.Data;
using HebrewBooks.Data.Repositories;
using HebrewBooks.Infrastructure.Paths;
using HebrewBooks.Infrastructure.Settings;
using HebrewBooks.Search;
using HebrewBooks.Services.Search;
using Microsoft.Extensions.Logging.Abstractions;

namespace HebrewBooks.Cli;

internal static class Program
{
	private sealed class InBookRequest
	{
		public string? FileName { get; set; }

		public string? Q { get; set; }

		public string? DisplayQuery { get; set; }

		public int? Proximity { get; set; }

		public int Fuzziness { get; set; }

		public bool Hybur { get; set; }

		public bool Roots { get; set; }

		public bool Gematria { get; set; }

		public bool Spelling { get; set; }

		public bool NumberGender { get; set; }

		public bool Aramaic { get; set; }

		public bool Rashetevot { get; set; }

		public bool RequireWordOrder { get; set; }

		public bool RashiOcr { get; set; }
	}

	private sealed class SearchRequest
	{
		public string? Q { get; set; }

		public int? Proximity { get; set; }

		public int? Fuzziness { get; set; }

		public int? Max { get; set; }

		public int? Limit { get; set; }

		public bool Hybur { get; set; }

		public bool Roots { get; set; }

		public bool Gematria { get; set; }

		public bool Spelling { get; set; }

		public bool NumberGender { get; set; }

		public bool Aramaic { get; set; }

		public bool Rashetevot { get; set; }

		public bool FirstWord { get; set; }

		public bool LastWord { get; set; }

		public bool RequireWordOrder { get; set; }

		public bool RashiOcr { get; set; }

		public bool ExcludePersonal { get; set; }

		public string? Sort { get; set; }

		public string[]? Corpus { get; set; }

		public string[]? RestrictFileIds { get; set; }
	}

	private const string InstallScriptTemplate = "# HebrewBooks client installer (generated by hbsearch). Shows a WPF install window.\n$ErrorActionPreference = 'Stop'\n$authority   = '__AUTHORITY__'\n$searchHost  = '__SEARCHHOST__'\n$searchPort  = __SEARCHPORT__\n$networkBase = '__NETBASE__'\n$shareUser   = '__SHAREUSER__'\n$sharePass   = '__SHAREPASS__'\n$setupUrlNet = '__SETUPURL_NET__'\n$setupUrlLan = 'http://' + $authority + '/Setup.exe'\n\nAdd-Type -AssemblyName PresentationFramework\n\n$xaml = @'\n<Window xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation'\n        xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'\n        Title='התקנת ארון הספרים הדיגיטלי' Height='250' Width='470'\n        WindowStartupLocation='CenterScreen' ResizeMode='NoResize' FlowDirection='RightToLeft'\n        Background='#F3F4F6'>\n  <Grid Margin='26'>\n    <Grid.RowDefinitions>\n      <RowDefinition Height='Auto'/>\n      <RowDefinition Height='*'/>\n      <RowDefinition Height='Auto'/>\n      <RowDefinition Height='Auto'/>\n    </Grid.RowDefinitions>\n    <TextBlock Grid.Row='0' Text='\ud83d\udcda ארון הספרים הדיגיטלי' FontSize='22' FontWeight='Bold' Foreground='#1F2937'/>\n    <TextBlock x:Name='StatusText' Grid.Row='1' Text='מתחיל בהתקנה...' FontSize='15' Foreground='#374151'\n               TextWrapping='Wrap' VerticalAlignment='Center' Margin='0,18'/>\n    <ProgressBar x:Name='Bar' Grid.Row='2' Height='10' IsIndeterminate='True' Foreground='#2563EB'\n                 Background='#E5E7EB' BorderThickness='0'/>\n    <Button x:Name='CloseBtn' Grid.Row='3' Content='סגור' Width='120' Height='36' Margin='0,20,0,0'\n            HorizontalAlignment='Left' Visibility='Collapsed' Background='#2563EB' Foreground='White'\n            BorderThickness='0' FontSize='14'/>\n  </Grid>\n</Window>\n'@\n\n[xml]$xamlXml = $xaml\n$win = [Windows.Markup.XamlReader]::Load((New-Object System.Xml.XmlNodeReader $xamlXml))\n$status   = $win.FindName('StatusText')\n$bar      = $win.FindName('Bar')\n$closeBtn = $win.FindName('CloseBtn')\n$closeBtn.Add_Click({ $win.Close() })\n\n$script:state     = 0\n$script:proc      = $null\n$script:setupTmp  = $null\n$script:dlFromNet = $false\n$script:total     = 0      # total bytes of the Setup being downloaded (0 = unknown -> indeterminate bar)\n$script:dlLabel   = ''     # base 'downloading from ...' text; the live percent is appended to it\n\nfunction Finish-Ok {\n    $script:timer.Stop()\n    $bar.IsIndeterminate = $false\n    $bar.Value = 100\n    $status.Text = 'ההתקנה הושלמה! אפשר להפעיל את ארון הספרים הדיגיטלי.'\n    $closeBtn.Visibility = 'Visible'\n}\nfunction Finish-Err($m) {\n    $script:timer.Stop()\n    $bar.IsIndeterminate = $false\n    $bar.Foreground = '#DC2626'\n    $status.Text = 'שגיאה: ' + $m\n    $closeBtn.Visibility = 'Visible'\n}\nfunction Start-Download($url) {\n    # Download via a child PowerShell + Invoke-WebRequest — curl.exe is NOT present on every station\n    # (its absence raised 'cannot find the file' and broke even the LAN fallback). The child sets\n    # ProgressPreference=SilentlyContinue (IWR -OutFile is very slow otherwise) and exits 1 on any web\n    # error so state 4 falls back to the LAN server. Polled via -PassThru so the window stays responsive.\n    $cmd = '$ProgressPreference=''SilentlyContinue''; try { Invoke-WebRequest -Uri ''' + $url + ''' -OutFile ''' + $script:setupTmp + ''' -UseBasicParsing } catch { exit 1 }'\n    $script:proc = Start-Process -FilePath 'powershell.exe' -PassThru -WindowStyle Hidden -ArgumentList @('-NoProfile','-Command',$cmd)\n}\n\n$script:timer = New-Object System.Windows.Threading.DispatcherTimer\n$script:timer.Interval = [TimeSpan]::FromMilliseconds(300)\n$script:timer.Add_Tick({\n  try {\n    switch ($script:state) {\n      0 {\n        # Write the server connection BEFORE installing, so an auto-launch of the app reads it.\n        $status.Text = 'מגדיר את החיבור לשרת...'\n        $cfgDir  = Join-Path $env:APPDATA 'HebrewBooks'\n        New-Item -ItemType Directory -Force -Path $cfgDir | Out-Null\n        $cfgPath = Join-Path $cfgDir 'settings.json'\n        if (Test-Path $cfgPath) { $cfg = Get-Content $cfgPath -Raw -Encoding UTF8 | ConvertFrom-Json } else { $cfg = [pscustomobject]@{} }\n        if (-not $cfg.Paths) { $cfg | Add-Member -NotePropertyName 'Paths' -NotePropertyValue ([pscustomobject]@{}) -Force }\n        # Master switch (root level) — without it every Effective* path getter returns null and the host/UNC below are ignored.\n        $cfg | Add-Member -NotePropertyName 'NetworkInstall' -NotePropertyValue $true -Force\n        $cfg.Paths | Add-Member -NotePropertyName 'SearchServiceHost' -NotePropertyValue $searchHost -Force\n        $cfg.Paths | Add-Member -NotePropertyName 'SearchServicePort' -NotePropertyValue ([int]$searchPort) -Force\n        if ($networkBase) {\n          # The shared base on the server holds Books / indexes / Otzraya / Personal AND the master\n          # Katalog.db. Stations read those from the share (derived from NetworkBasePath) but must NOT\n          # open the catalog directly off the SMB share: a WAL SQLite file over SMB throws 'database is\n          # locked' / 'disk I/O error' under cross-station contention and crashed catalog load. So the\n          # DATA ROOT is LOCAL — CatalogSync copies the master down to it on every launch and the app\n          # reads a fast, writable LOCAL catalog. (Earlier builds set the data root = the UNC share,\n          # which is what caused the crashes.) Per-user LocalAppData needs no admin and keeps the big\n          # catalog out of the roaming profile.\n          $localRoot = Join-Path $env:LOCALAPPDATA 'HebrewBooks\\Data'\n          New-Item -ItemType Directory -Force -Path $localRoot | Out-Null\n          $cfg.Paths | Add-Member -NotePropertyName 'NetworkBasePath' -NotePropertyValue $networkBase -Force\n          $cfg.Paths | Add-Member -NotePropertyName 'LastDataRootPath' -NotePropertyValue $localRoot -Force\n          # Clear any remembered volume serial from a prior (UNC-rooted) install so DataRootResolver\n          # doesn't lock onto the wrong volume — it re-finds the LOCAL root via LastDataRootPath.\n          $cfg.Paths | Add-Member -NotePropertyName 'DataVolumeSerial' -NotePropertyValue 0 -Force\n        }\n        ($cfg | ConvertTo-Json -Depth 30) | Set-Content -Path $cfgPath -Encoding UTF8\n        $script:state = 1\n      }\n      1 {\n        # Auto-connect to the SMB share (read-only account) so the user never types share creds.\n        # Best-effort: a hiccup here (e.g. already connected with other creds) must NOT fail the install.\n        if ($shareUser -and $networkBase) {\n          $status.Text = 'מתחבר לתיקייה המשותפת בשרת...'\n          try {\n            $shareRoot = $networkBase\n            if ($networkBase -match '^(\\\\\\\\[^\\\\]+\\\\[^\\\\]+)') { $shareRoot = $matches[1] }\n            & cmdkey /add:$searchHost /user:$shareUser /pass:$sharePass | Out-Null\n            & net use $shareRoot /user:$shareUser $sharePass /persistent:yes 2>$null | Out-Null\n          } catch {}\n        }\n        $script:state = 2\n      }\n      2 {\n        # Internet-first probe — a child PowerShell HEAD request against the GitHub release Setup, with\n        # its own short timeout. (A ranged GET failed: GitHub doesn't forward Range through the CDN\n        # redirect; HEAD follows the redirect and returns 200.) Non-blocking — state 3 polls it.\n        $status.Text = 'בודק חיבור לאינטרנט...'\n        $script:setupTmp = Join-Path $env:TEMP ('HebrewBooks-Setup-' + [guid]::NewGuid().ToString('N') + '.exe')\n        $pcmd = '$ProgressPreference=''SilentlyContinue''; try { Invoke-WebRequest -Uri ''' + $setupUrlNet + ''' -Method Head -TimeoutSec 8 -UseBasicParsing | Out-Null } catch { exit 1 }'\n        $script:proc = Start-Process -FilePath 'powershell.exe' -PassThru -WindowStyle Hidden -ArgumentList @('-NoProfile','-Command',$pcmd)\n        $script:state = 3\n      }\n      3 {\n        # Probe finished → internet reachable (exit 0) downloads from GitHub; otherwise from the LAN server.\n        if ($script:proc.HasExited) {\n          if ($script:proc.ExitCode -eq 0) { $script:dlLabel = 'מוריד את תוכנת ההתקנה מהאינטרנט (מהיר)'; $script:dlFromNet = $true;  $dlUrl = $setupUrlNet }\n          else                             { $script:dlLabel = 'מוריד את תוכנת ההתקנה מהשרת המקומי';     $script:dlFromNet = $false; $dlUrl = $setupUrlLan }\n          $status.Text = $script:dlLabel + '...'\n          # Total size for a REAL percent bar (best-effort). The source is already known-reachable so\n          # this HEAD is quick; if Content-Length is missing the bar simply stays indeterminate.\n          $script:total = 0\n          try { $hr = Invoke-WebRequest -Uri $dlUrl -Method Head -UseBasicParsing -TimeoutSec 10; $cl = $hr.Headers['Content-Length']; if ($cl) { $script:total = [int64]$cl } } catch {}\n          if ($script:total -gt 0) { $bar.IsIndeterminate = $false; $bar.Value = 0 }\n          Start-Download $dlUrl\n          $script:state = 4\n        }\n      }\n      4 {\n        # Live percent from the growing temp file vs the known total (when Content-Length was available).\n        if ($script:total -gt 0 -and (Test-Path $script:setupTmp)) {\n          $pct = [int](100 * (Get-Item $script:setupTmp).Length / $script:total)\n          if ($pct -gt 99) { $pct = 99 }\n          $bar.Value = $pct\n          $status.Text = $script:dlLabel + ' — ' + $pct + '%'\n        }\n        if ($script:proc.HasExited) {\n          $ok = ($script:proc.ExitCode -eq 0) -and (Test-Path $script:setupTmp) -and ((Get-Item $script:setupTmp).Length -gt 100000)\n          if ($ok) {\n            if ($script:total -gt 0) { $bar.Value = 100 }\n            $script:state = 5\n          } elseif ($script:dlFromNet) {\n            # Internet download failed mid-way → fall back to the LAN server, stay in this state.\n            $script:dlFromNet = $false\n            $script:dlLabel = 'מוריד את תוכנת ההתקנה מהשרת המקומי'\n            $status.Text = $script:dlLabel + '...'\n            Remove-Item $script:setupTmp -Force -ErrorAction SilentlyContinue\n            $script:total = 0\n            try { $hr = Invoke-WebRequest -Uri $setupUrlLan -Method Head -UseBasicParsing -TimeoutSec 10; $cl = $hr.Headers['Content-Length']; if ($cl) { $script:total = [int64]$cl } } catch {}\n            Start-Download $setupUrlLan\n          } else {\n            throw 'הורדת תוכנת ההתקנה נכשלה.'\n          }\n        }\n      }\n      5 {\n        $status.Text = 'מתקין את התוכנה...'\n        $script:proc = Start-Process -FilePath $script:setupTmp -PassThru\n        $script:state = 6\n      }\n      6 {\n        if ($script:proc.HasExited) {\n          Remove-Item $script:setupTmp -Force -ErrorAction SilentlyContinue\n          Finish-Ok\n        }\n      }\n    }\n  } catch {\n    Finish-Err $_.Exception.Message\n  }\n})\n$script:timer.Start()\n$win.ShowDialog() | Out-Null\n";

	private const string LandingPageTemplate = "<!doctype html>\n<html lang=\"he\" dir=\"rtl\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>התקנת ארון הספרים הדיגיטלי</title>\n<style>\n  body { font-family: Segoe UI, Arial, sans-serif; background:#f3f4f6; margin:0; padding:0;\n         display:flex; min-height:100vh; align-items:center; justify-content:center; }\n  .card { background:#fff; max-width:560px; width:92%; border-radius:16px; padding:40px 36px;\n          box-shadow:0 10px 40px rgba(0,0,0,.12); text-align:center; }\n  h1 { margin:0 0 8px; color:#1f2937; font-size:26px; }\n  p { color:#4b5563; line-height:1.7; font-size:16px; }\n  .btn { display:inline-block; margin:22px 0 6px; background:#2563eb; color:#fff; text-decoration:none;\n         font-size:20px; font-weight:600; padding:16px 44px; border-radius:12px; }\n  .btn:hover { background:#1d4ed8; }\n  .steps { text-align:right; color:#374151; font-size:15px; background:#f9fafb; border-radius:10px;\n           padding:14px 20px; margin-top:20px; }\n  .warn { color:#b45309; background:#fffbeb; border-radius:10px; padding:10px; font-size:15px; }\n  details { margin-top:18px; color:#6b7280; font-size:14px; text-align:right; }\n  code { background:#111827; color:#e5e7eb; padding:8px 12px; border-radius:8px; display:block;\n         direction:ltr; margin-top:8px; font-size:13px; }\n</style>\n</head>\n<body>\n  <div class=\"card\">\n    <h1>\ud83d\udcda ארון הספרים הדיגיטלי</h1>\n    <p>להתקנת התוכנה במחשב זה והגדרתה אוטומטית מול השרת, לחץ על הכפתור:</p>\n    <a class=\"btn\" href=\"/install.bat\" download>התקן עכשיו</a>\n    __READYNOTE__\n    <div class=\"steps\">\n      <b>מה עכשיו?</b><br>\n      1. ירד הקובץ <b>Install-HebrewBooks.bat</b> — פתח אותו (לחיצה כפולה).<br>\n      2. אם תופיע אזהרת אבטחה של Windows — לחץ ״מידע נוסף״ ואז ״הפעל בכל זאת״.<br>\n      3. ייפתח חלון שמתקין ומגדיר את הכול. בסיום אפשר להפעיל את התוכנה.\n    </div>\n    <details>\n      <summary>התקנה ידנית (למתקדמים)</summary>\n      <p>הרץ ב-PowerShell:</p>\n      <code>irm http://__AUTHORITY__/install | iex</code>\n    </details>\n  </div>\n</body>\n</html>\n";

	private const string InstallBatTemplate = "@echo off\nstart \"HebrewBooks\" /min powershell -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -Command \"iex(irm 'http://__AUTHORITY__/install')\"\nexit\n";

	private static volatile string? _servedInstaller;

	private const string OfflineSetupAsset = "HebrewBooks-offline-Setup.exe";

	private static readonly HttpClient Http = new HttpClient(new HttpClientHandler
	{
		AllowAutoRedirect = true
	})
	{
		Timeout = TimeSpan.FromMinutes(20.0)
	};

	private static readonly JsonSerializerOptions JsonIn = new JsonSerializerOptions(JsonSerializerDefaults.Web);

	private static readonly JsonSerializerOptions JsonOut = new JsonSerializerOptions
	{
		Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
	};

	private static string VpkCacheDir => Path.Combine(AppContext.BaseDirectory, "vpk-cache");

	private static async Task<int> Main(string[] args)
	{
		Console.OutputEncoding = Encoding.UTF8;
		Options opts;
		try
		{
			opts = Options.Parse(args);
		}
		catch (ArgUsageException ex)
		{
			Console.Error.WriteLine("error: " + ex.Message);
			Console.Error.WriteLine();
			Options.PrintUsage(Console.Error);
			return 1;
		}
		if (opts.ShowHelp)
		{
			Options.PrintUsage(Console.Out);
			return 0;
		}
		if (!opts.Serve && string.IsNullOrWhiteSpace(opts.Query))
		{
			Console.Error.WriteLine("error: no query text given.");
			Console.Error.WriteLine();
			Options.PrintUsage(Console.Error);
			return 1;
		}
		BookshelfOptions options;
		string dataRoot;
		try
		{
			JsonSettingsStore jsonSettingsStore = new JsonSettingsStore();
			options = jsonSettingsStore.Load();
			dataRoot = new DataRootResolver(jsonSettingsStore).Resolve(args);
		}
		catch (DataRootNotFoundException ex2)
		{
			Console.Error.WriteLine("error: " + ex2.Message);
			return 2;
		}
		PathResolver paths = new PathResolver(dataRoot, options);
		Console.Error.WriteLine("data-root: " + paths.DataDriveRoot);
		SqliteConnectionFactory sqliteConnectionFactory = new SqliteConnectionFactory(paths.CatalogDbPath);
		sqliteConnectionFactory.EnsureSchema();
		CatalogRepository catalog = new CatalogRepository(sqliteConnectionFactory);
		DtSearchNetEngine engine = new DtSearchNetEngine(new EngineOptions());
		PopularitySnapshot popularity = new PopularitySnapshot(paths);
		SearchOrchestrator orchestrator = new SearchOrchestrator(engine, catalog, paths, popularity, NullLogger<SearchOrchestrator>.Instance);
		try
		{
			await orchestrator.EnsureIndexOpenAsync();
			return (!opts.Serve) ? (await RunOneShotAsync(opts, paths, engine, orchestrator)) : (await ServeAsync(opts, paths, engine, orchestrator));
		}
		catch (Exception ex3)
		{
			Console.Error.WriteLine("error: " + ex3.Message);
			return 3;
		}
	}

	private static async Task<int> RunOneShotAsync(Options opts, PathResolver paths, DtSearchNetEngine engine, SearchOrchestrator orchestrator)
	{
		string transformed;
		SearchQuery searchQuery = BuildQuery(opts, paths, engine, out transformed);
		if ((object)searchQuery == null)
		{
			Console.Error.WriteLine("error: query reduced to empty after transform.");
			return 1;
		}
		Console.Error.WriteLine("query: " + transformed);
		IReadOnlyList<SearchResultRow> readOnlyList = await orchestrator.RunAsync(searchQuery, opts.Sort);
		IEnumerable<SearchResultRow> source = readOnlyList;
		if (opts.ExcludePersonal)
		{
			source = source.Where((SearchResultRow r) => !string.Equals(r.Book.SourceType, "Personal", StringComparison.Ordinal));
		}
		int? limit = opts.Limit;
		if (limit.HasValue)
		{
			int valueOrDefault = limit.GetValueOrDefault();
			source = source.Take(valueOrDefault);
		}
		List<SearchResultRow> list = source.ToList();
		EmitResults(opts, transformed, readOnlyList.Count, list);
		Console.Error.WriteLine($"matched {readOnlyList.Count} document(s); emitted {list.Count}.");
		return 0;
	}

	private static async Task<int> ServeAsync(Options opts, PathResolver paths, DtSearchNetEngine engine, SearchOrchestrator orchestrator)
	{
		SemaphoreSlim gate = new SemaphoreSlim(1, 1);
		using HttpListener listener = new HttpListener();
		string text = $"http://+:{opts.Port}/";
		listener.Prefixes.Add(text);
		try
		{
			listener.Start();
		}
		catch (HttpListenerException ex)
		{
			Console.Error.WriteLine("failed to listen on " + text + ": " + ex.Message);
			Console.Error.WriteLine($"On Windows the URL must be reserved once (run as admin):\n  netsh http add urlacl url={text} user=Everyone\n…or run this process elevated.");
			return 4;
		}
		Console.Error.WriteLine($"hbsearch serving on {text}  (data-root: {paths.DataDriveRoot})");
		Console.Error.WriteLine("Endpoints: GET /search?q=<query>&...  |  GET /health    (Ctrl+C to stop)");
		if (opts.InstallEnabled)
		{
			string text2 = Path.Combine(AppContext.BaseDirectory, "installer-cache");
			string text3 = Path.Combine(text2, "Setup.exe");
			_servedInstaller = (File.Exists(text3) ? text3 : ((!string.IsNullOrWhiteSpace(opts.InstallerPath) && File.Exists(opts.InstallerPath)) ? opts.InstallerPath : null));
			Console.Error.WriteLine((_servedInstaller == null) ? "Client install ENABLED: GET /install + GET /Setup.exe  (no local installer yet — will download from GitHub when online)" : ("Client install ENABLED: GET /install + GET /Setup.exe  (serving: " + _servedInstaller + ")"));
			if (opts.InstallerUpdate)
			{
				RefreshInstallerAsync(opts, text2, text3);
			}
			else
			{
				Console.Error.WriteLine("  installer auto-update disabled (--no-installer-update): serving local/cached only.");
			}
		}
		if (opts.UpdateFeedEnabled)
		{
			Console.Error.WriteLine($"Client auto-update ENABLED: GET /vpk/*  (LAN Velopack feed for '{opts.UpdateChannel}' stations, mirrored from {opts.InstallerRepo})");
			RefreshVpkFeedAsync(opts);
		}
		while (true)
		{
			HttpListenerContext ctx;
			try
			{
				ctx = await listener.GetContextAsync();
			}
			catch
			{
				break;
			}
			HandleRequestAsync(ctx, opts, paths, engine, orchestrator, gate);
		}
		return 0;
	}

	private static async Task HandleRequestAsync(HttpListenerContext ctx, Options opts, PathResolver paths, DtSearchNetEngine engine, SearchOrchestrator orchestrator, SemaphoreSlim gate)
	{
		HttpListenerResponse resp = ctx.Response;
		try
		{
			resp.Headers["Access-Control-Allow-Origin"] = "*";
			string text = ctx.Request.Url?.AbsolutePath ?? "/";
			if (opts.InstallEnabled && (string.Equals(text, "/", StringComparison.Ordinal) || string.Equals(text, "/index.html", StringComparison.OrdinalIgnoreCase)))
			{
				await HandleLandingPageAsync(ctx, opts, resp);
				return;
			}
			if (string.Equals(text, "/install.bat", StringComparison.OrdinalIgnoreCase) || string.Equals(text, "/install.cmd", StringComparison.OrdinalIgnoreCase))
			{
				await HandleInstallBatAsync(ctx, opts, resp);
				return;
			}
			if (string.Equals(text, "/install", StringComparison.OrdinalIgnoreCase) || string.Equals(text, "/install.ps1", StringComparison.OrdinalIgnoreCase))
			{
				await HandleInstallScriptAsync(ctx, opts, resp);
				return;
			}
			if (string.Equals(text, "/Setup.exe", StringComparison.OrdinalIgnoreCase) || string.Equals(text, "/download/setup", StringComparison.OrdinalIgnoreCase))
			{
				await HandleInstallerDownloadAsync(opts, resp);
				return;
			}
			if (text.StartsWith("/vpk/", StringComparison.OrdinalIgnoreCase))
			{
				await HandleVpkAsync(opts, text, resp);
				return;
			}
			if (string.Equals(text, "/health", StringComparison.OrdinalIgnoreCase))
			{
				await WriteTextAsync(resp, 200, "application/json; charset=utf-8", "{\"ok\":true,\"service\":\"hbsearch\"}");
				return;
			}
			if (string.Equals(text, "/inbook", StringComparison.OrdinalIgnoreCase))
			{
				await HandleInBookAsync(ctx.Request, resp, paths, engine, orchestrator, gate);
				return;
			}
			if (!string.Equals(text, "/search", StringComparison.OrdinalIgnoreCase))
			{
				await WriteTextAsync(resp, 404, "application/json; charset=utf-8", JsonError("unknown route (use /search, /inbook, /health, /install or /Setup.exe)"));
				return;
			}
			Options ro;
			IReadOnlyList<string> restrictFileIds;
			try
			{
				(ro, restrictFileIds) = await ParseRequestAsync(ctx.Request);
			}
			catch (ArgUsageException ex)
			{
				await WriteTextAsync(resp, 400, "application/json; charset=utf-8", JsonError(ex.Message));
				return;
			}
			catch (JsonException ex2)
			{
				await WriteTextAsync(resp, 400, "application/json; charset=utf-8", JsonError("bad JSON body: " + ex2.Message));
				return;
			}
			if (string.IsNullOrWhiteSpace(ro.Query))
			{
				await WriteTextAsync(resp, 400, "application/json; charset=utf-8", JsonError("missing 'q'"));
				return;
			}
			await gate.WaitAsync();
			IReadOnlyList<SearchResultRow> readOnlyList2;
			try
			{
				SearchQuery searchQuery;
				try
				{
					searchQuery = BuildQuery(ro, paths, engine, out string _, restrictFileIds);
				}
				catch (Exception ex3)
				{
					await WriteTextAsync(resp, 400, "application/json; charset=utf-8", JsonError(ex3.Message));
					return;
				}
				IReadOnlyList<SearchResultRow> readOnlyList = (((object)searchQuery != null) ? (await orchestrator.RunAsync(searchQuery, ro.Sort)) : Array.Empty<SearchResultRow>());
				readOnlyList2 = readOnlyList;
			}
			finally
			{
				gate.Release();
			}
			IEnumerable<SearchResultRow> enumerable = readOnlyList2;
			if (ro.ExcludePersonal)
			{
				enumerable = enumerable.Where((SearchResultRow r) => !string.Equals(r.Book.SourceType, "Personal", StringComparison.Ordinal));
			}
			int? limit = ro.Limit;
			if (limit.HasValue)
			{
				int valueOrDefault = limit.GetValueOrDefault();
				enumerable = enumerable.Take(valueOrDefault);
			}
			resp.StatusCode = 200;
			resp.SendChunked = true;
			resp.ContentType = "application/x-ndjson; charset=utf-8";
			await using StreamWriter writer = new StreamWriter(resp.OutputStream, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
			int n = 0;
			foreach (SearchResultRow item in enumerable)
			{
				await writer.WriteLineAsync(JsonSerializer.Serialize(ToDto(item), JsonOut));
				int num = n + 1;
				n = num;
				if (num % 100 == 0)
				{
					await writer.FlushAsync();
				}
			}
			await writer.FlushAsync();
		}
		catch (Exception ex4)
		{
			try
			{
				Console.Error.WriteLine("request error: " + ex4.Message);
			}
			catch
			{
			}
		}
		finally
		{
			try
			{
				resp.OutputStream.Close();
			}
			catch
			{
			}
		}
	}

	private static async Task HandleInstallerDownloadAsync(Options opts, HttpListenerResponse resp)
	{
		string servedInstaller = _servedInstaller;
		if (!opts.InstallEnabled || string.IsNullOrWhiteSpace(servedInstaller) || !File.Exists(servedInstaller))
		{
			await WriteTextAsync(resp, 404, "application/json; charset=utf-8", JsonError("installer not available yet (no local --installer and no download cached)"));
			return;
		}
		FileInfo fileInfo = new FileInfo(servedInstaller);
		resp.StatusCode = 200;
		resp.ContentType = "application/octet-stream";
		resp.ContentLength64 = fileInfo.Length;
		resp.Headers["Content-Disposition"] = "attachment; filename=Setup.exe";
		await using FileStream fs = File.OpenRead(servedInstaller);
		await fs.CopyToAsync(resp.OutputStream).ConfigureAwait(continueOnCapturedContext: false);
	}

	private static async Task RefreshInstallerAsync(Options opts, string cacheDir, string cachedSetup)
	{
		_ = 6;
		try
		{
			Directory.CreateDirectory(cacheDir);
			string versionFile = Path.Combine(cacheDir, "version.txt");
			string latestTag;
			using (CancellationTokenSource cts = new CancellationTokenSource(TimeSpan.FromSeconds(8.0)))
			{
				using HttpRequestMessage req = new HttpRequestMessage(HttpMethod.Get, "https://api.github.com/repos/" + opts.InstallerRepo + "/releases/latest");
				req.Headers.UserAgent.ParseAdd("hbsearch-installer-updater");
				req.Headers.Accept.ParseAdd("application/vnd.github+json");
				using HttpResponseMessage apiResp = await Http.SendAsync(req, cts.Token).ConfigureAwait(continueOnCapturedContext: false);
				apiResp.EnsureSuccessStatusCode();
				using JsonDocument jsonDocument = JsonDocument.Parse(await apiResp.Content.ReadAsStringAsync(cts.Token).ConfigureAwait(continueOnCapturedContext: false));
				latestTag = (jsonDocument.RootElement.TryGetProperty("tag_name", out var value) ? value.GetString() : null);
			}
			if (string.IsNullOrWhiteSpace(latestTag))
			{
				Console.Error.WriteLine("installer-update: could not read latest release tag; keeping local/cached installer.");
				return;
			}
			string a = ((!File.Exists(versionFile) || !File.Exists(cachedSetup)) ? null : (await File.ReadAllTextAsync(versionFile).ConfigureAwait(continueOnCapturedContext: false)).Trim());
			if (string.Equals(a, latestTag, StringComparison.Ordinal))
			{
				_servedInstaller = cachedSetup;
				Console.Error.WriteLine("installer-update: cached offline Setup is current (" + latestTag + ").");
				return;
			}
			string requestUri = "https://github.com/" + opts.InstallerRepo + "/releases/latest/download/HebrewBooks-offline-Setup.exe";
			Console.Error.WriteLine("installer-update: downloading offline Setup " + latestTag + " ...");
			string tmp = cachedSetup + ".download";
			using (HttpResponseMessage apiResp = await Http.GetAsync(requestUri, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(continueOnCapturedContext: false))
			{
				apiResp.EnsureSuccessStatusCode();
				await using FileStream fs = new FileStream(tmp, FileMode.Create, FileAccess.Write, FileShare.None);
				await apiResp.Content.CopyToAsync(fs).ConfigureAwait(continueOnCapturedContext: false);
			}
			try
			{
				if (File.Exists(cachedSetup))
				{
					File.Delete(cachedSetup);
				}
			}
			catch
			{
			}
			File.Move(tmp, cachedSetup);
			await File.WriteAllTextAsync(versionFile, latestTag).ConfigureAwait(continueOnCapturedContext: false);
			_servedInstaller = cachedSetup;
			long value2 = new FileInfo(cachedSetup).Length / 1048576;
			Console.Error.WriteLine($"installer-update: now serving offline Setup {latestTag} ({value2} MB).");
		}
		catch (Exception ex)
		{
			Console.Error.WriteLine($"installer-update: skipped ({ex.GetType().Name}: {ex.Message}); serving local/cached installer.");
		}
	}

	private static bool IsSafeVpkName(string name)
	{
		int length = name.Length;
		if (length > 0 && length < 200 && name.All(delegate(char c)
		{
			bool flag = char.IsLetterOrDigit(c);
			if (!flag)
			{
				bool flag2 = ((c == '-' || c == '.' || c == '_') ? true : false);
				flag = flag2;
			}
			return flag;
		}))
		{
			if (!name.EndsWith(".nupkg", StringComparison.OrdinalIgnoreCase))
			{
				if (name.StartsWith("releases.", StringComparison.OrdinalIgnoreCase))
				{
					return name.EndsWith(".json", StringComparison.OrdinalIgnoreCase);
				}
				return false;
			}
			return true;
		}
		return false;
	}

	private static async Task HandleVpkAsync(Options opts, string path, HttpListenerResponse resp)
	{
		if (!opts.UpdateFeedEnabled)
		{
			await WriteTextAsync(resp, 404, "application/json; charset=utf-8", JsonError("update feed not enabled on this server"));
			return;
		}
		string text = Uri.UnescapeDataString(path.Substring("/vpk/".Length));
		if (!IsSafeVpkName(text))
		{
			await WriteTextAsync(resp, 404, "application/json; charset=utf-8", JsonError("unknown update asset"));
			return;
		}
		bool isJson = text.EndsWith(".json", StringComparison.OrdinalIgnoreCase);
		string text2 = await MirrorVpkAssetAsync(opts, text, isJson).ConfigureAwait(continueOnCapturedContext: false);
		if (text2 == null)
		{
			await WriteTextAsync(resp, 502, "application/json; charset=utf-8", JsonError("update asset unavailable (not cached and could not be fetched from the releases repo)"));
		}
		else
		{
			await ServeFileAsync(resp, text2, isJson ? "application/json; charset=utf-8" : "application/octet-stream").ConfigureAwait(continueOnCapturedContext: false);
		}
	}

	private static async Task<string?> MirrorVpkAssetAsync(Options opts, string name, bool forceRefresh)
	{
		string local = Path.Combine(VpkCacheDir, name);
		bool haveCached = File.Exists(local);
		if (haveCached && !forceRefresh)
		{
			return local;
		}
		try
		{
			Directory.CreateDirectory(VpkCacheDir);
			string requestUri = "https://github.com/" + opts.InstallerRepo + "/releases/latest/download/" + name;
			string tmp = local + ".download";
			using (HttpResponseMessage dl = await Http.GetAsync(requestUri, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(continueOnCapturedContext: false))
			{
				dl.EnsureSuccessStatusCode();
				await using FileStream fs = new FileStream(tmp, FileMode.Create, FileAccess.Write, FileShare.None);
				await dl.Content.CopyToAsync(fs).ConfigureAwait(continueOnCapturedContext: false);
			}
			try
			{
				if (File.Exists(local))
				{
					File.Delete(local);
				}
			}
			catch
			{
			}
			File.Move(tmp, local);
			return local;
		}
		catch (Exception ex)
		{
			if (!haveCached)
			{
				Console.Error.WriteLine($"vpk-feed: could not fetch {name} ({ex.GetType().Name}: {ex.Message}).");
			}
			return haveCached ? local : null;
		}
	}

	private static async Task RefreshVpkFeedAsync(Options opts)
	{
		_ = 2;
		try
		{
			string name = "releases." + opts.UpdateChannel + ".json";
			string text = await MirrorVpkAssetAsync(opts, name, forceRefresh: true).ConfigureAwait(continueOnCapturedContext: false);
			if (text == null)
			{
				Console.Error.WriteLine("vpk-feed: '" + opts.UpdateChannel + "' feed not available yet (offline or not published); will serve lazily on demand.");
				return;
			}
			using JsonDocument doc = JsonDocument.Parse(await File.ReadAllTextAsync(text).ConfigureAwait(continueOnCapturedContext: false));
			if (!TryGetPropertyCI(doc.RootElement, "assets", out var value) || value.ValueKind != JsonValueKind.Array)
			{
				return;
			}
			int warmed = 0;
			int total = 0;
			foreach (JsonElement item in value.EnumerateArray())
			{
				JsonElement value2;
				string text2 = (TryGetPropertyCI(item, "fileName", out value2) ? value2.GetString() : null);
				if (!string.IsNullOrWhiteSpace(text2) && text2.EndsWith(".nupkg", StringComparison.OrdinalIgnoreCase) && IsSafeVpkName(text2))
				{
					total++;
					if (!File.Exists(Path.Combine(VpkCacheDir, text2)) && await MirrorVpkAssetAsync(opts, text2, forceRefresh: false).ConfigureAwait(continueOnCapturedContext: false) != null)
					{
						warmed++;
					}
				}
			}
			Console.Error.WriteLine($"vpk-feed: '{opts.UpdateChannel}' ready ({total} package(s); {warmed} newly cached).");
		}
		catch (Exception ex)
		{
			Console.Error.WriteLine($"vpk-feed: pre-warm skipped ({ex.GetType().Name}: {ex.Message}); serving lazily on demand.");
		}
	}

	private static bool TryGetPropertyCI(JsonElement el, string name, out JsonElement value)
	{
		if (el.ValueKind == JsonValueKind.Object)
		{
			foreach (JsonProperty item in el.EnumerateObject())
			{
				if (string.Equals(item.Name, name, StringComparison.OrdinalIgnoreCase))
				{
					value = item.Value;
					return true;
				}
			}
		}
		value = default(JsonElement);
		return false;
	}

	private static async Task ServeFileAsync(HttpListenerResponse resp, string file, string contentType)
	{
		FileInfo fileInfo = new FileInfo(file);
		resp.StatusCode = 200;
		resp.ContentType = contentType;
		resp.ContentLength64 = fileInfo.Length;
		await using FileStream fs = File.OpenRead(file);
		await fs.CopyToAsync(resp.OutputStream).ConfigureAwait(continueOnCapturedContext: false);
	}

	private static async Task HandleInstallScriptAsync(HttpListenerContext ctx, Options opts, HttpListenerResponse resp)
	{
		if (!opts.InstallEnabled)
		{
			await WriteTextAsync(resp, 404, "text/plain; charset=utf-8", "# install is not enabled on this server (start hbsearch with --installer <Setup.exe> or --enable-install)");
			return;
		}
		string servedInstaller = _servedInstaller;
		if (string.IsNullOrWhiteSpace(servedInstaller) || !File.Exists(servedInstaller))
		{
			await WriteTextAsync(resp, 503, "text/plain; charset=utf-8", "# installer not ready yet (downloading the latest from GitHub, or no offline file present). Try again shortly.");
			return;
		}
		string text = ResolveAuthority(ctx, opts);
		string s = text.Split(':')[0];
		string s2 = opts.ClientBase ?? "";
		string s3 = "https://github.com/" + opts.InstallerRepo + "/releases/latest/download/HebrewBooks-offline-Setup.exe";
		string body = "# HebrewBooks client installer (generated by hbsearch). Shows a WPF install window.\n$ErrorActionPreference = 'Stop'\n$authority   = '__AUTHORITY__'\n$searchHost  = '__SEARCHHOST__'\n$searchPort  = __SEARCHPORT__\n$networkBase = '__NETBASE__'\n$shareUser   = '__SHAREUSER__'\n$sharePass   = '__SHAREPASS__'\n$setupUrlNet = '__SETUPURL_NET__'\n$setupUrlLan = 'http://' + $authority + '/Setup.exe'\n\nAdd-Type -AssemblyName PresentationFramework\n\n$xaml = @'\n<Window xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation'\n        xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'\n        Title='התקנת ארון הספרים הדיגיטלי' Height='250' Width='470'\n        WindowStartupLocation='CenterScreen' ResizeMode='NoResize' FlowDirection='RightToLeft'\n        Background='#F3F4F6'>\n  <Grid Margin='26'>\n    <Grid.RowDefinitions>\n      <RowDefinition Height='Auto'/>\n      <RowDefinition Height='*'/>\n      <RowDefinition Height='Auto'/>\n      <RowDefinition Height='Auto'/>\n    </Grid.RowDefinitions>\n    <TextBlock Grid.Row='0' Text='\ud83d\udcda ארון הספרים הדיגיטלי' FontSize='22' FontWeight='Bold' Foreground='#1F2937'/>\n    <TextBlock x:Name='StatusText' Grid.Row='1' Text='מתחיל בהתקנה...' FontSize='15' Foreground='#374151'\n               TextWrapping='Wrap' VerticalAlignment='Center' Margin='0,18'/>\n    <ProgressBar x:Name='Bar' Grid.Row='2' Height='10' IsIndeterminate='True' Foreground='#2563EB'\n                 Background='#E5E7EB' BorderThickness='0'/>\n    <Button x:Name='CloseBtn' Grid.Row='3' Content='סגור' Width='120' Height='36' Margin='0,20,0,0'\n            HorizontalAlignment='Left' Visibility='Collapsed' Background='#2563EB' Foreground='White'\n            BorderThickness='0' FontSize='14'/>\n  </Grid>\n</Window>\n'@\n\n[xml]$xamlXml = $xaml\n$win = [Windows.Markup.XamlReader]::Load((New-Object System.Xml.XmlNodeReader $xamlXml))\n$status   = $win.FindName('StatusText')\n$bar      = $win.FindName('Bar')\n$closeBtn = $win.FindName('CloseBtn')\n$closeBtn.Add_Click({ $win.Close() })\n\n$script:state     = 0\n$script:proc      = $null\n$script:setupTmp  = $null\n$script:dlFromNet = $false\n$script:total     = 0      # total bytes of the Setup being downloaded (0 = unknown -> indeterminate bar)\n$script:dlLabel   = ''     # base 'downloading from ...' text; the live percent is appended to it\n\nfunction Finish-Ok {\n    $script:timer.Stop()\n    $bar.IsIndeterminate = $false\n    $bar.Value = 100\n    $status.Text = 'ההתקנה הושלמה! אפשר להפעיל את ארון הספרים הדיגיטלי.'\n    $closeBtn.Visibility = 'Visible'\n}\nfunction Finish-Err($m) {\n    $script:timer.Stop()\n    $bar.IsIndeterminate = $false\n    $bar.Foreground = '#DC2626'\n    $status.Text = 'שגיאה: ' + $m\n    $closeBtn.Visibility = 'Visible'\n}\nfunction Start-Download($url) {\n    # Download via a child PowerShell + Invoke-WebRequest — curl.exe is NOT present on every station\n    # (its absence raised 'cannot find the file' and broke even the LAN fallback). The child sets\n    # ProgressPreference=SilentlyContinue (IWR -OutFile is very slow otherwise) and exits 1 on any web\n    # error so state 4 falls back to the LAN server. Polled via -PassThru so the window stays responsive.\n    $cmd = '$ProgressPreference=''SilentlyContinue''; try { Invoke-WebRequest -Uri ''' + $url + ''' -OutFile ''' + $script:setupTmp + ''' -UseBasicParsing } catch { exit 1 }'\n    $script:proc = Start-Process -FilePath 'powershell.exe' -PassThru -WindowStyle Hidden -ArgumentList @('-NoProfile','-Command',$cmd)\n}\n\n$script:timer = New-Object System.Windows.Threading.DispatcherTimer\n$script:timer.Interval = [TimeSpan]::FromMilliseconds(300)\n$script:timer.Add_Tick({\n  try {\n    switch ($script:state) {\n      0 {\n        # Write the server connection BEFORE installing, so an auto-launch of the app reads it.\n        $status.Text = 'מגדיר את החיבור לשרת...'\n        $cfgDir  = Join-Path $env:APPDATA 'HebrewBooks'\n        New-Item -ItemType Directory -Force -Path $cfgDir | Out-Null\n        $cfgPath = Join-Path $cfgDir 'settings.json'\n        if (Test-Path $cfgPath) { $cfg = Get-Content $cfgPath -Raw -Encoding UTF8 | ConvertFrom-Json } else { $cfg = [pscustomobject]@{} }\n        if (-not $cfg.Paths) { $cfg | Add-Member -NotePropertyName 'Paths' -NotePropertyValue ([pscustomobject]@{}) -Force }\n        # Master switch (root level) — without it every Effective* path getter returns null and the host/UNC below are ignored.\n        $cfg | Add-Member -NotePropertyName 'NetworkInstall' -NotePropertyValue $true -Force\n        $cfg.Paths | Add-Member -NotePropertyName 'SearchServiceHost' -NotePropertyValue $searchHost -Force\n        $cfg.Paths | Add-Member -NotePropertyName 'SearchServicePort' -NotePropertyValue ([int]$searchPort) -Force\n        if ($networkBase) {\n          # The shared base on the server holds Books / indexes / Otzraya / Personal AND the master\n          # Katalog.db. Stations read those from the share (derived from NetworkBasePath) but must NOT\n          # open the catalog directly off the SMB share: a WAL SQLite file over SMB throws 'database is\n          # locked' / 'disk I/O error' under cross-station contention and crashed catalog load. So the\n          # DATA ROOT is LOCAL — CatalogSync copies the master down to it on every launch and the app\n          # reads a fast, writable LOCAL catalog. (Earlier builds set the data root = the UNC share,\n          # which is what caused the crashes.) Per-user LocalAppData needs no admin and keeps the big\n          # catalog out of the roaming profile.\n          $localRoot = Join-Path $env:LOCALAPPDATA 'HebrewBooks\\Data'\n          New-Item -ItemType Directory -Force -Path $localRoot | Out-Null\n          $cfg.Paths | Add-Member -NotePropertyName 'NetworkBasePath' -NotePropertyValue $networkBase -Force\n          $cfg.Paths | Add-Member -NotePropertyName 'LastDataRootPath' -NotePropertyValue $localRoot -Force\n          # Clear any remembered volume serial from a prior (UNC-rooted) install so DataRootResolver\n          # doesn't lock onto the wrong volume — it re-finds the LOCAL root via LastDataRootPath.\n          $cfg.Paths | Add-Member -NotePropertyName 'DataVolumeSerial' -NotePropertyValue 0 -Force\n        }\n        ($cfg | ConvertTo-Json -Depth 30) | Set-Content -Path $cfgPath -Encoding UTF8\n        $script:state = 1\n      }\n      1 {\n        # Auto-connect to the SMB share (read-only account) so the user never types share creds.\n        # Best-effort: a hiccup here (e.g. already connected with other creds) must NOT fail the install.\n        if ($shareUser -and $networkBase) {\n          $status.Text = 'מתחבר לתיקייה המשותפת בשרת...'\n          try {\n            $shareRoot = $networkBase\n            if ($networkBase -match '^(\\\\\\\\[^\\\\]+\\\\[^\\\\]+)') { $shareRoot = $matches[1] }\n            & cmdkey /add:$searchHost /user:$shareUser /pass:$sharePass | Out-Null\n            & net use $shareRoot /user:$shareUser $sharePass /persistent:yes 2>$null | Out-Null\n          } catch {}\n        }\n        $script:state = 2\n      }\n      2 {\n        # Internet-first probe — a child PowerShell HEAD request against the GitHub release Setup, with\n        # its own short timeout. (A ranged GET failed: GitHub doesn't forward Range through the CDN\n        # redirect; HEAD follows the redirect and returns 200.) Non-blocking — state 3 polls it.\n        $status.Text = 'בודק חיבור לאינטרנט...'\n        $script:setupTmp = Join-Path $env:TEMP ('HebrewBooks-Setup-' + [guid]::NewGuid().ToString('N') + '.exe')\n        $pcmd = '$ProgressPreference=''SilentlyContinue''; try { Invoke-WebRequest -Uri ''' + $setupUrlNet + ''' -Method Head -TimeoutSec 8 -UseBasicParsing | Out-Null } catch { exit 1 }'\n        $script:proc = Start-Process -FilePath 'powershell.exe' -PassThru -WindowStyle Hidden -ArgumentList @('-NoProfile','-Command',$pcmd)\n        $script:state = 3\n      }\n      3 {\n        # Probe finished → internet reachable (exit 0) downloads from GitHub; otherwise from the LAN server.\n        if ($script:proc.HasExited) {\n          if ($script:proc.ExitCode -eq 0) { $script:dlLabel = 'מוריד את תוכנת ההתקנה מהאינטרנט (מהיר)'; $script:dlFromNet = $true;  $dlUrl = $setupUrlNet }\n          else                             { $script:dlLabel = 'מוריד את תוכנת ההתקנה מהשרת המקומי';     $script:dlFromNet = $false; $dlUrl = $setupUrlLan }\n          $status.Text = $script:dlLabel + '...'\n          # Total size for a REAL percent bar (best-effort). The source is already known-reachable so\n          # this HEAD is quick; if Content-Length is missing the bar simply stays indeterminate.\n          $script:total = 0\n          try { $hr = Invoke-WebRequest -Uri $dlUrl -Method Head -UseBasicParsing -TimeoutSec 10; $cl = $hr.Headers['Content-Length']; if ($cl) { $script:total = [int64]$cl } } catch {}\n          if ($script:total -gt 0) { $bar.IsIndeterminate = $false; $bar.Value = 0 }\n          Start-Download $dlUrl\n          $script:state = 4\n        }\n      }\n      4 {\n        # Live percent from the growing temp file vs the known total (when Content-Length was available).\n        if ($script:total -gt 0 -and (Test-Path $script:setupTmp)) {\n          $pct = [int](100 * (Get-Item $script:setupTmp).Length / $script:total)\n          if ($pct -gt 99) { $pct = 99 }\n          $bar.Value = $pct\n          $status.Text = $script:dlLabel + ' — ' + $pct + '%'\n        }\n        if ($script:proc.HasExited) {\n          $ok = ($script:proc.ExitCode -eq 0) -and (Test-Path $script:setupTmp) -and ((Get-Item $script:setupTmp).Length -gt 100000)\n          if ($ok) {\n            if ($script:total -gt 0) { $bar.Value = 100 }\n            $script:state = 5\n          } elseif ($script:dlFromNet) {\n            # Internet download failed mid-way → fall back to the LAN server, stay in this state.\n            $script:dlFromNet = $false\n            $script:dlLabel = 'מוריד את תוכנת ההתקנה מהשרת המקומי'\n            $status.Text = $script:dlLabel + '...'\n            Remove-Item $script:setupTmp -Force -ErrorAction SilentlyContinue\n            $script:total = 0\n            try { $hr = Invoke-WebRequest -Uri $setupUrlLan -Method Head -UseBasicParsing -TimeoutSec 10; $cl = $hr.Headers['Content-Length']; if ($cl) { $script:total = [int64]$cl } } catch {}\n            Start-Download $setupUrlLan\n          } else {\n            throw 'הורדת תוכנת ההתקנה נכשלה.'\n          }\n        }\n      }\n      5 {\n        $status.Text = 'מתקין את התוכנה...'\n        $script:proc = Start-Process -FilePath $script:setupTmp -PassThru\n        $script:state = 6\n      }\n      6 {\n        if ($script:proc.HasExited) {\n          Remove-Item $script:setupTmp -Force -ErrorAction SilentlyContinue\n          Finish-Ok\n        }\n      }\n    }\n  } catch {\n    Finish-Err $_.Exception.Message\n  }\n})\n$script:timer.Start()\n$win.ShowDialog() | Out-Null\n".Replace("__AUTHORITY__", Q(text)).Replace("__SEARCHHOST__", Q(s)).Replace("__SEARCHPORT__", opts.Port.ToString(CultureInfo.InvariantCulture))
			.Replace("__NETBASE__", Q(s2))
			.Replace("__SHAREUSER__", Q(opts.ShareUser ?? ""))
			.Replace("__SHAREPASS__", Q(opts.SharePass ?? ""))
			.Replace("__SETUPURL_NET__", Q(s3));
		await WriteTextAsync(resp, 200, "text/plain; charset=utf-8", body);
		static string Q(string text2)
		{
			return text2.Replace("'", "''");
		}
	}

	private static string ResolveAuthority(HttpListenerContext ctx, Options opts)
	{
		if (!string.IsNullOrWhiteSpace(opts.AdvertiseHost))
		{
			if (!opts.AdvertiseHost.Contains(':'))
			{
				return $"{opts.AdvertiseHost}:{opts.Port}";
			}
			return opts.AdvertiseHost;
		}
		string userHostName = ctx.Request.UserHostName;
		if (!string.IsNullOrWhiteSpace(userHostName))
		{
			if (!userHostName.Contains(':'))
			{
				return $"{userHostName}:{opts.Port}";
			}
			return userHostName;
		}
		return $"localhost:{opts.Port}";
	}

	private static async Task HandleLandingPageAsync(HttpListenerContext ctx, Options opts, HttpListenerResponse resp)
	{
		string value = ResolveAuthority(ctx, opts);
		string newValue = ((!string.IsNullOrWhiteSpace(_servedInstaller) && File.Exists(_servedInstaller)) ? "" : "<p class=\"warn\">⏳ תוכנת ההתקנה עדיין בהורדה בשרת. נסה שוב בעוד דקה.</p>");
		string body = "<!doctype html>\n<html lang=\"he\" dir=\"rtl\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>התקנת ארון הספרים הדיגיטלי</title>\n<style>\n  body { font-family: Segoe UI, Arial, sans-serif; background:#f3f4f6; margin:0; padding:0;\n         display:flex; min-height:100vh; align-items:center; justify-content:center; }\n  .card { background:#fff; max-width:560px; width:92%; border-radius:16px; padding:40px 36px;\n          box-shadow:0 10px 40px rgba(0,0,0,.12); text-align:center; }\n  h1 { margin:0 0 8px; color:#1f2937; font-size:26px; }\n  p { color:#4b5563; line-height:1.7; font-size:16px; }\n  .btn { display:inline-block; margin:22px 0 6px; background:#2563eb; color:#fff; text-decoration:none;\n         font-size:20px; font-weight:600; padding:16px 44px; border-radius:12px; }\n  .btn:hover { background:#1d4ed8; }\n  .steps { text-align:right; color:#374151; font-size:15px; background:#f9fafb; border-radius:10px;\n           padding:14px 20px; margin-top:20px; }\n  .warn { color:#b45309; background:#fffbeb; border-radius:10px; padding:10px; font-size:15px; }\n  details { margin-top:18px; color:#6b7280; font-size:14px; text-align:right; }\n  code { background:#111827; color:#e5e7eb; padding:8px 12px; border-radius:8px; display:block;\n         direction:ltr; margin-top:8px; font-size:13px; }\n</style>\n</head>\n<body>\n  <div class=\"card\">\n    <h1>\ud83d\udcda ארון הספרים הדיגיטלי</h1>\n    <p>להתקנת התוכנה במחשב זה והגדרתה אוטומטית מול השרת, לחץ על הכפתור:</p>\n    <a class=\"btn\" href=\"/install.bat\" download>התקן עכשיו</a>\n    __READYNOTE__\n    <div class=\"steps\">\n      <b>מה עכשיו?</b><br>\n      1. ירד הקובץ <b>Install-HebrewBooks.bat</b> — פתח אותו (לחיצה כפולה).<br>\n      2. אם תופיע אזהרת אבטחה של Windows — לחץ ״מידע נוסף״ ואז ״הפעל בכל זאת״.<br>\n      3. ייפתח חלון שמתקין ומגדיר את הכול. בסיום אפשר להפעיל את התוכנה.\n    </div>\n    <details>\n      <summary>התקנה ידנית (למתקדמים)</summary>\n      <p>הרץ ב-PowerShell:</p>\n      <code>irm http://__AUTHORITY__/install | iex</code>\n    </details>\n  </div>\n</body>\n</html>\n".Replace("__AUTHORITY__", WebUtility.HtmlEncode(value)).Replace("__READYNOTE__", newValue);
		await WriteTextAsync(resp, 200, "text/html; charset=utf-8", body);
	}

	private static async Task HandleInstallBatAsync(HttpListenerContext ctx, Options opts, HttpListenerResponse resp)
	{
		if (!opts.InstallEnabled)
		{
			await WriteTextAsync(resp, 404, "text/plain; charset=utf-8", "install is not enabled on this server");
			return;
		}
		string newValue = ResolveAuthority(ctx, opts);
		string body = "@echo off\nstart \"HebrewBooks\" /min powershell -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -Command \"iex(irm 'http://__AUTHORITY__/install')\"\nexit\n".Replace("__AUTHORITY__", newValue).Replace("\r\n", "\n").Replace("\n", "\r\n");
		resp.Headers["Content-Disposition"] = "attachment; filename=Install-HebrewBooks.bat";
		await WriteTextAsync(resp, 200, "application/octet-stream", body);
	}

	private static async Task HandleInBookAsync(HttpListenerRequest req, HttpListenerResponse resp, PathResolver paths, DtSearchNetEngine engine, SearchOrchestrator orchestrator, SemaphoreSlim gate)
	{
		if (!string.Equals(req.HttpMethod, "POST", StringComparison.OrdinalIgnoreCase))
		{
			await WriteTextAsync(resp, 405, "application/json; charset=utf-8", JsonError("use POST /inbook"));
			return;
		}
		InBookRequest body;
		try
		{
			using StreamReader reader = new StreamReader(req.InputStream, req.ContentEncoding ?? Encoding.UTF8);
			body = JsonSerializer.Deserialize<InBookRequest>(await reader.ReadToEndAsync().ConfigureAwait(continueOnCapturedContext: false), JsonIn) ?? new InBookRequest();
		}
		catch (JsonException ex)
		{
			await WriteTextAsync(resp, 400, "application/json; charset=utf-8", JsonError("bad JSON body: " + ex.Message));
			return;
		}
		if (string.IsNullOrWhiteSpace(body.FileName) || string.IsNullOrWhiteSpace(body.Q))
		{
			await WriteTextAsync(resp, 400, "application/json; charset=utf-8", JsonError("fileName and q are required"));
			return;
		}
		HebAramMap aramMap = (body.Aramaic ? new HebAramMap(() => HebAramMap.ReadFileText(paths.HebAramPath)) : null);
		await gate.WaitAsync();
		InBookHitInfo inBookHitInfo2;
		try
		{
			int? proximity = body.Proximity;
			int defaultProximity;
			if (proximity.HasValue)
			{
				int valueOrDefault = proximity.GetValueOrDefault();
				if (valueOrDefault > 0)
				{
					defaultProximity = valueOrDefault;
					goto IL_03d5;
				}
			}
			defaultProximity = 30;
			goto IL_03d5;
			IL_03d5:
			QueryBuildOptions options = new QueryBuildOptions(AddPrefixLetters: body.Hybur, FirstWordOnly: false, LastWordOnly: false, RasheyTevot: body.Rashetevot ? RasheyTevotMap.LoadFromFile(paths.RasheyTevotPath) : null, ExpandRoots: body.Roots, ExpandNumberGender: body.NumberGender, ExpandGematria: body.Gematria, ExpandSpelling: body.Spelling, Aramaic: aramMap, IndexWordFilter: engine.FilterIndexedWords, MaxTotalExpansions: 200, RequireWordOrder: body.RequireWordOrder, DefaultProximity: defaultProximity, ExpandRashiOcr: body.RashiOcr);
			string text = QueryBuilder.Build(body.Q, options);
			string displayQuery = (string.IsNullOrWhiteSpace(body.DisplayQuery) ? body.Q : body.DisplayQuery);
			InBookHitInfo inBookHitInfo = ((!string.IsNullOrWhiteSpace(text)) ? (await orchestrator.GetInBookHitsCachedAsync(body.FileName, text, displayQuery, body.Hybur, body.Roots, body.NumberGender, body.Gematria, body.Spelling, aramMap, Math.Clamp(body.Fuzziness, 0, 10)).ConfigureAwait(continueOnCapturedContext: false)) : new InBookHitInfo(0, Array.Empty<int>(), Array.Empty<string>()));
			inBookHitInfo2 = inBookHitInfo;
		}
		finally
		{
			gate.Release();
		}
		var value = new
		{
			hitCount = inBookHitInfo2.HitCount,
			pages = inBookHitInfo2.Pages,
			matchedTerms = inBookHitInfo2.MatchedTerms,
			highlightXml = inBookHitInfo2.HighlightXml
		};
		await WriteTextAsync(resp, 200, "application/json; charset=utf-8", JsonSerializer.Serialize(value, JsonOut));
	}

	private static Options OptionsFromQuery(NameValueCollection qs)
	{
		List<string> args = new List<string>();
		string text = qs["q"] ?? qs["query"];
		if (!string.IsNullOrWhiteSpace(text))
		{
			args.Add(text);
		}
		Flag("hybur", "--hybur");
		Flag("roots", "--roots");
		Flag("gematria", "--gematria");
		Flag("spelling", "--spelling");
		Flag("number-gender", "--number-gender");
		Flag("aramaic", "--aramaic");
		Flag("rashetevot", "--rashetevot");
		Flag("first-word", "--first-word");
		Flag("last-word", "--last-word");
		Flag("require-word-order", "--require-word-order");
		Flag("rashi-ocr", "--rashi-ocr");
		Flag("exclude-personal", "--exclude-personal");
		Val("proximity", "--proximity");
		Val("fuzziness", "--fuzziness");
		Val("max", "--max");
		Val("limit", "--limit");
		Val("sort", "--sort");
		Val("corpus", "--corpus");
		return Options.Parse(args.ToArray());
		void Flag(string param, string flag)
		{
			string text2 = qs[param];
			if (text2 != null && (text2.Length == 0 || text2 == "1" || text2.Equals("true", StringComparison.OrdinalIgnoreCase)))
			{
				args.Add(flag);
			}
		}
		void Val(string param, string flag)
		{
			string text2 = qs[param];
			if (!string.IsNullOrEmpty(text2))
			{
				args.Add(flag);
				args.Add(text2);
			}
		}
	}

	private static async Task<(Options opts, IReadOnlyList<string>? restrictFileIds)> ParseRequestAsync(HttpListenerRequest req)
	{
		if (!string.Equals(req.HttpMethod, "POST", StringComparison.OrdinalIgnoreCase))
		{
			return (opts: OptionsFromQuery(req.QueryString), restrictFileIds: null);
		}
		using StreamReader reader = new StreamReader(req.InputStream, req.ContentEncoding ?? Encoding.UTF8);
		SearchRequest searchRequest = JsonSerializer.Deserialize<SearchRequest>(await reader.ReadToEndAsync().ConfigureAwait(continueOnCapturedContext: false), JsonIn) ?? new SearchRequest();
		List<string> args = new List<string>();
		if (!string.IsNullOrWhiteSpace(searchRequest.Q))
		{
			args.Add(searchRequest.Q);
		}
		Flag(searchRequest.Hybur, "--hybur");
		Flag(searchRequest.Roots, "--roots");
		Flag(searchRequest.Gematria, "--gematria");
		Flag(searchRequest.Spelling, "--spelling");
		Flag(searchRequest.NumberGender, "--number-gender");
		Flag(searchRequest.Aramaic, "--aramaic");
		Flag(searchRequest.Rashetevot, "--rashetevot");
		Flag(searchRequest.FirstWord, "--first-word");
		Flag(searchRequest.LastWord, "--last-word");
		Flag(searchRequest.RequireWordOrder, "--require-word-order");
		Flag(searchRequest.RashiOcr, "--rashi-ocr");
		Flag(searchRequest.ExcludePersonal, "--exclude-personal");
		Val(searchRequest.Proximity, "--proximity");
		Val(searchRequest.Fuzziness, "--fuzziness");
		Val(searchRequest.Max, "--max");
		Val(searchRequest.Limit, "--limit");
		if (!string.IsNullOrEmpty(searchRequest.Sort))
		{
			args.Add("--sort");
			args.Add(searchRequest.Sort);
		}
		string[] corpus = searchRequest.Corpus;
		if (corpus != null && corpus.Length > 0)
		{
			args.Add("--corpus");
			args.Add(string.Join(',', searchRequest.Corpus));
		}
		corpus = searchRequest.RestrictFileIds;
		string[] item = ((corpus != null && corpus.Length > 0) ? searchRequest.RestrictFileIds : null);
		return (opts: Options.Parse(args.ToArray()), restrictFileIds: item);
		void Flag(bool on, string f)
		{
			if (on)
			{
				args.Add(f);
			}
		}
		void Val(int? v, string f)
		{
			if (v.HasValue)
			{
				int valueOrDefault = v.GetValueOrDefault();
				args.Add(f);
				args.Add(valueOrDefault.ToString(CultureInfo.InvariantCulture));
			}
		}
	}

	private static async Task WriteTextAsync(HttpListenerResponse resp, int status, string contentType, string body)
	{
		resp.StatusCode = status;
		resp.ContentType = contentType;
		byte[] bytes = Encoding.UTF8.GetBytes(body);
		resp.ContentLength64 = bytes.Length;
		await resp.OutputStream.WriteAsync(bytes);
	}

	private static string JsonError(string msg)
	{
		return JsonSerializer.Serialize(new
		{
			ok = false,
			error = msg
		}, JsonOut);
	}

	private static SearchQuery? BuildQuery(Options opts, PathResolver paths, DtSearchNetEngine engine, out string transformed, IReadOnlyList<string>? restrictFileIds = null)
	{
		transformed = "";
		QueryBuildOptions options = new QueryBuildOptions(opts.Proximity, opts.Hybur, opts.FirstWord, opts.LastWord, opts.RasheyTevot ? RasheyTevotMap.LoadFromFile(paths.RasheyTevotPath) : null, opts.Roots, opts.NumberGender, opts.Gematria, opts.Spelling, opts.Aramaic ? new HebAramMap(() => HebAramMap.ReadFileText(paths.HebAramPath)) : null, engine.FilterIndexedWords, 200, RequireWordOrder: opts.RequireWordOrder, ExpandRashiOcr: opts.RashiOcr, ExpandWeakLetters: opts.WeakLetters);
		string text = QueryBuilder.Build(opts.Query, options);
		if (string.IsNullOrWhiteSpace(text))
		{
			return null;
		}
		transformed = text;
		IReadOnlyList<string> restrictToIndexPaths = null;
		if (opts.Corpora.Count > 0)
		{
			List<string> list = new List<string>();
			if (opts.Corpora.Contains("PDF"))
			{
				list.Add(paths.IndexesRoot);
			}
			if (opts.Corpora.Contains("Text"))
			{
				list.Add(paths.OtzrayaIndexPath);
			}
			if (opts.Corpora.Contains("Personal"))
			{
				list.Add(paths.PersonalIndexPath);
			}
			if (list.Count > 0)
			{
				restrictToIndexPaths = list;
			}
		}
		return new SearchQuery(transformed, opts.Proximity, opts.Hybur, IncludeNumbers: true, opts.MaxFiles, opts.Fuzziness, restrictFileIds, restrictToIndexPaths, QueryBuilder.CountMatchWords(opts.Query));
	}

	private static object ToDto(SearchResultRow r)
	{
		return new
		{
			fileId = r.Book.FileID,
			bookName = r.Book.BookName,
			authorName = r.Book.AuthorName,
			printPlace = r.Book.PrintPlace,
			printYear = r.Book.PrintYear,
			countPage = r.Book.CountPage,
			categories = r.Book.Categories,
			sourceType = r.Book.SourceType,
			relativePath = r.Book.RelativePath,
			hitCount = r.HitCount,
			firstHitPage = r.PageNumber
		};
	}

	private static void EmitResults(Options opts, string transformed, int total, List<SearchResultRow> rows)
	{
		if (opts.Format == OutputFormat.Jsonl)
		{
			foreach (SearchResultRow row in rows)
			{
				Console.Out.WriteLine(JsonSerializer.Serialize(ToDto(row), JsonOut));
			}
			return;
		}
		string value = JsonSerializer.Serialize(new
		{
			query = opts.Query,
			transformedQuery = transformed,
			totalMatched = total,
			returned = rows.Count,
			results = rows.Select(ToDto).ToList()
		}, new JsonSerializerOptions(JsonOut)
		{
			WriteIndented = opts.Pretty
		});
		Console.Out.WriteLine(value);
	}
}
